# -*- coding: utf-8 -*-
"""nlp_project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rh4a5htRc3IbP2q39BtklIV8h2SDyUqn
"""

import pandas as pd
import numpy as
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('vader_lexicon') np
import re #regular expressions for cleaning the data
import nltk # Natural Language Toolkit (NLTK)
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.corpus import stopwords # to remove the verbs unwated words
from nltk.sentiment import SentimentIntensityAnalyzer  #
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize # segments
from collections import Counter
from wordcloud import WordCloud # Ensure WordCloud class is imported

# downloading required nltk files

"""creating sample customer review


"""

data = {
    "Review": [
        "The product quality is excellent and delivery was very fast.",
        "Very bad packaging and the item was damaged.",
        "Customer service was helpful and responsive.",
        "The delivery was delayed and support team did not respond.",
        "Amazing product. Worth the money.",
        "Poor quality product and terrible experience.",
        "Fast shipping and good packaging.",
        "The product stopped working after two days.",
        "Excellent service and great quality.",
        "Late delivery and bad customer support."
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

print("customer reviews datadsets")
print(df.head())

stop_words = set(stopwords.words('english'))
def clean_text(text):
  text = text.lower()
  print('lower case',text)
  text = re.sub(r'[^a-zA-Z\s]','',text)
  print("special character",text)

  words = word_tokenize(text)
  print("tokenization",words)

  words = [word for word in words if word not in stop_words]
  print("stop words",words)

  cleaned_text = " ".join(words)

  return cleaned_text

nltk.download('punkt_tab')
df['cleaned_review'] = df['Review'].apply(clean_text)
print(df[['Review','cleaned_review']])

sia=SentimentIntensityAnalyzer()
def analyze_sentiment(review):
  score=sia.polarity_scores(review)
  compound=score['compound']
  if compound>=0.05:
    return 'positive'
  elif compound<=0.05:
    return 'negative'
  else:
    return 'neutral'
df['sentiment']=df['cleaned_review'].apply(analyze_sentiment)
print("\nsentiment analysis result")
print(df[['Review','sentiment']])

all_words =" ".join(df['cleaned_review'])
word_list =all_words.split()

word_freq=Counter(word_list)
print("\n top 10 common ")
print(word_freq.most_common(10))

negative_reviews = df[df['sentiment'] == 'Negative']
negative_words = " ".join(negative_reviews['cleaned_review'])
negative_words_list=negative_words.split()
complaint_freq=Counter(negative_words_list)
print("\n most common complainted")
print(complaint_freq.most_common(10))

sentiment_counts = df['sentiment'].value_counts()
plt.figure(figsize=(8,6))
sns.barplot(x=sentiment_counts.index,y=sentiment_counts.values)
plt.title('Sentiment Counts')
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.show()

wordcloud_generator = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(all_words)
plt.figure(figsize=(10,5))
plt.imshow(wordcloud_generator, interpolation='bilinear')
plt.axis('off')
plt.show()